### ISSUE TITLE
CircleCI test_lambda job failing

### ISSUE THREAD

**Issue by briankfitzwater** [GSA/grace-inventory-lambda#36]
```
--- FAIL: TestAccounts (0.20s)
    helpers_test.go:29: Accounts() failed: AccessDeniedException: You don't have permissions to access this resource.
        	status code: 400, request id: 5e34c99e-6dd5-11e9-aaad-658c768d4932
```

**Comment by briankfitzwater** [comment]
Looks like the `TF_VAR_role_name` environment variable needs to be updated for a role in the new master payer account.  @bryanlalexander What is the role in the master payer account for querying accounts?

**Comment by briankfitzwater** [comment]
I think I found it.  Testing now.

**Comment by bryanlalexander** [comment]
This should be accomplished via the `arn:aws:iam::$REMOTE_ACCOUNT_ID:role/OrganizationAccountAccessRole` in the remote account, during account creation the trust relationship is re-established with the management account. However, this feature may no longer be necessary moving forward as inventorying customer accounts isn't in scope any longer.

**Comment by briankfitzwater** [comment]
The `TF_VAR_orgrole` environment variable needed to be set.

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix grace-inventory-lambda CircleCI build/tests](https://trello.com/c/b2VfOJTJ/1253-fix-grace-inventory-lambda-circleci-build-tests)
